{
 "title": "Immich",
 "description": "Immich Dashboard\n\nhttps://github.com/emmekappa/immich-exporter",
 "tags": [ "immich" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "promsource", "label": "Prometheus Source", "query": "prometheus" },
   {
    "name": "Queues",
    "query": {
     "query": "label_values(immich_jobs_count,queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_storage_disk_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_storage_disk_use", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_storage_disk_available", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_storage_disk_usage_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Photo Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_photo_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Video Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_video_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs waiting",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_jobs_count{status=~\"waiting\", queue=~\"thumbnail_generation|face_detection|facial_recognition|metadata_extraction|smart_search|video_conversion\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "User Photos",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_statistics_user_photo_count",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "User Videos",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_statistics_user_video_count",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "User Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_user_usage", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Jobs paused",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_jobs_count{status=~\"paused\", queue=~\"thumbnail_generation|face_detection|facial_recognition|metadata_extraction|smart_search|video_conversion\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Thumbnail generation ETA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Thumbnail generation per minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(deriv(immich_jobs_count{queue=\"thumbnail_generation\", status=\"waiting\"}[10m])) * -60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending jobs: $Queues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 21 },
   "repeat": "Queues",
   "targets": [
    {
     "expr": "sum(immich_jobs_count{queue=\"$Queues\", status=~\"paused|waiting\"})",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}